import json

def build_resource_page(shell,head,sec,code,actions,root,D):
    proof=json.loads((root/'evidence/resource-readiness.json').read_text())
    body=proof['body']
    shell('power','Direct paid work',head('DIRECT USDC / EXTERNAL PROVIDER','THE RESERVE<br>BUYS THE WORK.','Three source searches. One retained journal.<br>Real vendor payment. Recoverable saved results.')+
        sec('readiness','01 / LIVE OFFER. PURCHASE TEST NEXT.',code('PROVIDER             EXA / DIRECT\nNETWORK              SOLANA MAINNET / USDC\nOFFERED SEARCH       0.007 USDC\nPLANNED TASKS        3\nPLANNED EXPENSE      0.021 USDC\nACTUAL PURCHASES     0 / AWAITING FUNDING')+
            '<p>Dated unsigned HTTP402 offer: '+body['observedAt']+'. This checks the vendor price and payment option. It does not prove a purchase. The new finite controller is prepared; its live funded test is still pending.</p>'+actions(('/evidence/resource-readiness.json','DATED OFFER / JSON'),('/docs#resource','INTEGRATION DOCS')))+
        sec('flow','02 / ONE FINITE CONTROLLER.',code('RESERVE -> QUOTE -> BUDGET CHECK\n                      |\n                   SIGN + BUY\n                      |\n               SAVE RAW RESPONSE\n                      |\n          VERIFY FINALIZED PAYMENT\n                      |\n            ACCEPT PRIMARY SOURCES\n                      |\n           BOOK EXPENSE -> NEXT TASK\n\nSAVED RESPONSE -> EXIT 76 -> RESTART\n                      |\n               SAME RECEIPT\n                      |\n                NO NEW PURCHASE')+
            '<p>The agent gathers three lists of official sources about Solana payments, x402 verification and Exa integration. At least two unique HTTPS sources must pass each result gate. Search results cannot change the wallet, destination or spending policy.</p>')+
        sec('budget','03 / PRINCIPAL. EXPENSE. RETURN.',code('DEDICATED RESERVE     1.000 USDC\nPROTECTED FLOOR      0.970 USDC\nMAX VENDOR EXPENSE   0.030 USDC\nEXPECTED EXPENSE     0.021 USDC\nEXPECTED RETURN      0.979 USDC\nBATTERY SDK FEE      0.000 USDC')+
            '<p>USDC goes to Exa\'s advertised recipient. The facilitator pays purchase gas; funding and return fees are separate. No OpenAI key or fiat cost estimate is used for this path. The SDK earns no revenue from these purchases.</p><p>The floor is enforced by trusted local software. A compromised owner signing key can bypass it. Hosted subscriptions and customer deposits are unavailable.</p>')+
        sec('run','04 / INSTALL. INSPECT. FUND ONCE.',code('cd chain\nnpm ci\ncd ..\npython3 paid_resource.py prepare\npython3 paid_resource.py probe\npython3 paid_resource.py status')+
            '<p>Preparation creates a private local wallet. Probe requests pricing without paying. Review the runbook and exact budget before enabling the finite paid run. Keys stay on your machine; this website cannot receive a private key or authorize a purchase.</p>'+actions(('/battery-pilot-kit.zip','DOWNLOAD SOURCE ZIP'),('https://github.com/sproutagentai/battery-agent-reserve','PUBLIC SOURCE'),('/developer/paid-resource.md','FUNDED RUN + RECOVERY')))+
        sec('limits','05 / THE RECOVERY BOUNDARY.',
            '<p>Fifteen new offline checks cover process exit/restart, replay, an unknown response, charged failures, principal return, locks and cryptographic payment guards. These checks use fault fixtures; they are not live payment evidence.</p><p>A saved response can recover without another purchase. If the response disappears before it reaches durable storage, the purchase stays uncertain. The provider has no documented result-retrieval endpoint, so BATTERY does not automatically buy it again. A rejected result can still have a real vendor charge.</p>'+actions(('/developer/data-contract.md','DATA + SOURCE CONTRACT'),('/developer/security.md','TRUST BOUNDARIES'),('/status','RELEASE GATES'))))
