def build_power_check(shell):
    tool='''<section id="power-check" class="power-check"><div class="tool-title"><div><span class="eyebrow">01 / THE POWER CHECK</span><h2>What’s left in the tank?</h2></div><span class="network-pill">Solana mainnet · read only</span></div>
<form id="wallet-form" class="wallet-form"><label for="wallet">Public Solana wallet</label><div class="wallet-entry"><input id="wallet" name="wallet" spellcheck="false" autocomplete="off" maxlength="44" placeholder="Paste a wallet address" required><button class="solid-button" type="submit" id="check-button">Check runway <span aria-hidden="true">↗</span></button></div></form>
<div class="check-hints"><span>No connection. No signature. No funds moved.</span><button id="example-wallet" type="button" class="inline-button">Try our closed test wallet ↗</button></div>
<p id="check-status" role="status" aria-live="polite" class="check-status">We read finalized SOL and USDC. Your wallet is sent to our server and Solana public RPC.</p>
<section id="power-result" class="power-result" hidden aria-label="Wallet power report"><div class="result-top"><div><span class="eyebrow">FINALIZED WALLET OBSERVATION</span><h3 id="wallet-label"></h3></div><a id="wallet-explorer" target="_blank" rel="noopener noreferrer">View on Solscan ↗</a></div>
<div class="balance-grid"><div><span>Self-paid gas</span><strong id="sol-balance"></strong><small>SOL · observed balance</small></div><div><span>Spendable USDC</span><strong id="usdc-balance"></strong><small>Canonical USDC · frozen excluded</small></div><div class="balance-note"><span id="account-kind"></span><p id="gas-note"></p></div></div>
<p id="observation-note" class="observation-note"></p>
<form id="estimate-form" class="estimate-form"><div><span class="eyebrow">YOUR ASSUMPTIONS</span><h3>Turn balance into runway.</h3><p>Enter the daily USDC spend you expect. We don’t infer burn from transfers.</p></div><label>Daily spend / USDC<input id="daily-spend" type="text" inputmode="decimal" placeholder="e.g. 2" maxlength="15" required></label><label>Keep untouched / USDC<input id="protected-floor" type="text" inputmode="decimal" value="0" maxlength="15" required></label><button type="submit" class="outline-button">Estimate runway ↗</button></form>
<p id="estimate-error" role="status" class="check-status"></p>
<div id="share-card" class="share-card" hidden><div class="card-brand">UNHALT <span>AGENT RUNWAY CARD</span></div><div class="card-runway"><strong id="runway-value"></strong><span>USDC runway / your spend estimate</span></div><div class="card-meter" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div><p class="meter-caption">0–7 days / USDC runway scale</p><p id="card-assumptions"></p><small id="card-observed"></small></div>
<div class="report-actions"><button id="save-card" type="button" class="solid-button" hidden>Save power card ↓</button><button id="share-report" type="button" class="outline-button">Copy report link ↗</button><button id="save-json" type="button" class="inline-button">Export observation JSON ↓</button></div>
<div id="report-link-box" class="report-link-box" hidden><label for="report-link">Share link / includes wallet and assumptions</label><input id="report-link" readonly></div><p class="report-limit">Sharing includes this public wallet and your estimates. A link rechecks current balances; a downloaded card keeps its observation date. USDC runway is an estimate, not provider credit or proof an agent is running. SOL fees, token rent and any USDC spent on gas are separate costs.</p></section></section>'''
    hero='''<section class="living-hero" aria-labelledby="living-title"><div class="living-copy"><h1 id="living-title">Let the work<br>live on.</h1><p>Reserve + recovery for Solana agents.<br>Saved work. Controlled restart. Open-source SDK.</p></div><img class="memory-art" src="/assets/second-life/hero.webp" alt="Two delicate coral and silver networks connected by one unbroken filament — a metaphor for retained work" width="2009" height="783" fetchpriority="high"><span class="memory-caption">MEMORY / RETAINED</span></section>'''
    below='''<section class="idea-strip"><span>THE PROBLEM IS SIMPLE.</span><h2>Smart agents.<br>Dumb ways to stop.</h2><p>The wallet has money. The next job still fails. Gas, provider credit and runtime state are different constraints. UNHALT makes the boundary visible — and keeps receipts so an owned runtime can recover.</p></section>
<section class="journey-grid"><article><span class="eyebrow">01 / KNOW</span><h3>Check the runway.</h3><p>Read the actual wallet. Add your burn rate. Get a dated power card you can keep or share.</p><a href="#power-check">Run a power check ↗</a></article><article><span class="eyebrow">02 / PROTECT</span><h3>Keep a floor.</h3><p>Use the SDK to reserve a worst-case job cost before dispatch. Unknown outcomes keep their hold.</p><a href="/docs#quickstart">Open the operator docs ↗</a></article><article><span class="eyebrow">03 / RESUME</span><h3>Keep the work.</h3><p>Persist the receipt. Recover the same owned runtime. Verify settlement before another task starts.</p><a href="/evidence">Inspect actual recovery ↗</a></article></section>
<section class="proof-banner"><div><span class="eyebrow">ACTUAL OWNED-AGENT CANARY</span><h2>Break it.<br>Keep the receipt.</h2><p>Three local-model tasks. Three finalized USDC settlements. Same-signature recovery. All principal returned. This is a bounded experiment, not a hosted-agent service.</p><a class="outline-button" href="/evidence">Read the evidence ↗</a></div><div class="proof-number">0<small>duplicate calls on replay<br>in the published integrated run</small></div></section>'''
    scripts='<script type="module" src="/wallet-check.mjs"></script>'
    tool=tool.replace('What’s left in the tank?','Check your wallet runway').replace('Paste a wallet address','Paste a public wallet address').replace('Check runway <span aria-hidden="true">↗</span>','Check wallet <img class="ui-icon" src="/assets/second-life/icons/arrow-right.svg" alt="" width="18" height="18">').replace('<section id="power-result"','<a class="check-proof" href="/evidence">Explore recovery proof <img class="ui-icon" src="/assets/second-life/icons/arrow-right.svg" alt="" width="18" height="18"></a><section id="power-result"')
    hero=hero.replace('<span class="memory-caption">MEMORY / RETAINED</span>','<span class="memory-caption">MEMORY / RETAINED</span><button class="memory-replay" type="button" hidden aria-label="Replay decorative energy transfer">Send pulse</button><button class="memory-toggle" type="button" hidden aria-pressed="false" aria-label="Pause decorative animation">Pause motion</button>')
    shell('','Let the work live on',hero+tool+below,scripts+'<script type="module" src="/memory-motion.mjs"></script>')
    shell('check','Wallet power check','<div class="check-page-head"><span class="eyebrow">UNHALT / READ-ONLY TOOL</span><h1>Check the runway.</h1><p>A real wallet observation. Your own spending assumptions.</p></div>'+tool,scripts)
