from pathlib import Path
import html,json,shutil
# Optional repository URL. Leave unset until the new owner is confirmed.
SOURCE='https://github.com/sproutagentai/battery-agent-reserve'
def build(shell,head,panel,D,BASE):
 root=Path(__file__).resolve().parent.parent
 report=json.loads((root/'evidence/live-agent.json').read_text()); exp=report['experiment']
 esc=html.escape
 def code(t):return '<pre class="code">'+esc(t)+'</pre>'
 def sec(id,title,body):return f'<section id="{id}" class="panel"><h2>{title}</h2>{body}</section>'
 def link(url,label):return f'<a class="text-button" href="{url}">[ {label} ]</a>'
 def actions(*links):return '<div class="actions">'+''.join(link(*l) for l in links if l[0])+'</div>'
 canary=json.loads((root/'evidence/reserve-svm.json').read_text())
 mainnet=json.loads((root/'evidence/mainnet-agent.json').read_text())
 mainExp=mainnet['experiment']
 mainTasks=''
 for i,r in enumerate(mainnet['checkpoint']['body']['results'],1):
  out=r['output'];mainTasks+=sec('main-task-'+str(i),f"RESEARCH {i:02d} / {out['model'].upper()}",'<p>'+esc(out['interpretation']['summary'])+'</p><p class="fine">Unedited model interpretation. Finalized mainnet slot: '+str(out['input']['observation']['slot'])+'. Not a trading recommendation or an oracle.</p>')
 financial=json.loads((root/'evidence/mainnet-canary.json').read_text()); fb=financial['body']
 receipt_list='<ol class="workflow">'+''.join('<li>'+esc(id.upper())+' / '+(f"{r['amountUsdc']/1e6:.2f} USDC" if r['amountUsdc'] else 'AUTHORIZATION')+' '+link('https://explorer.solana.com/tx/'+r['signature'],'FINALIZED TX')+'</li>' for id,r in fb['receipts'].items())+'</ol>'
 financial_summary=code('[ PASS ] 8 FINALIZED MAINNET TRANSACTIONS\n[ PASS ] 3 SETTLEMENTS / 0 REPLAY PAYMENTS\n[ PASS ] EXIT 74 -> SAME SIGNATURE RECOVERED\n[ PASS ] DELEGATION REVOKED / 5.00 USDC RETURNED')+'<p>October 5, 2026. A bounded financial experiment on Solana mainnet. Three 0.01 USDC settlements bind saved owned-agent results. The second transfer survived a deliberate process exit; replay created no new payment. All principal returned.</p><p class="fine">Inference ran locally before settlement. These transfers are test settlements to our own worker, not model-provider bills. The hosted paid-service release remains on hold.</p>'+actions(('/evidence/mainnet-canary.json','FINANCIAL PROOF / JSON'),(SOURCE,'INSPECT SOURCE'),('/developer/mainnet.md','REPRODUCE + VERIFY'))
 shell('mainnet','Mainnet financial proof',head('MAINNET / 05 OCT 2026 / FINALIZED CANARY','THE TRANSFER SURVIVED.<br>THE RESTART.','Real USDC. Bounded delegation.<br>Revoke. Return. Inspect every signature.')+
 sec('stage','01 / WHAT ACTUALLY SETTLED',financial_summary+'<button id="verify-financial-proof" class="text-button">[ VERIFY ARTIFACT HASH ]</button><pre id="financial-integrity" class="code" role="status">[ READY TO VERIFY ]</pre>')+
 sec('receipts','02 / EIGHT FINALIZED RECEIPTS',receipt_list+'<p class="fine">All links point to Solana mainnet. BATTERY transaction fees total 0.00004 SOL; sender fees are separate. Amounts are USDC transfers, not project revenue.</p>')+
 sec('policy','03 / CAPITAL IN. CAPITAL OUT.',code('FUNDED           5.00 USDC + 0.008 SOL\nEXCESS RETURN    2.00 USDC BEFORE SETUP\nREVIEWED RESERVE 3.00 USDC\nWORKER CAP       1.00 USDC / TOTAL / 24h\nTEST PAYMENTS    0.01 USDC x 3\nAFTER PAYMENT    2.97 OWNER / 0.03 WORKER\nRETURNED         5.00 USDC / ALL PRINCIPAL\nDELEGATION       CLOSED')+'<p>Fresh local owner and worker wallets. The chain bounds delegate identity, cumulative allowance, expiry and revocation. With no other delegations, the 1 USDC cap protects at least 2 USDC of the 3 USDC reserve from that worker. The owner can change or withdraw; per-task, daily and additional gas limits are runtime checks.</p><p>Remaining SOL and account rent stay locally operator-owned. This website cannot collect deposits or sign. No token or BATTERY custody program is deployed.</p>'+actions(('/evidence/mainnet-status.json','DATED STATUS'),('/developer/mainnet.md','BUDGET + TRUST BOUNDARIES')))+
 sec('recovery','04 / SAME TRANSFER. AFTER THE CRASH.',code('SAVE SIGNED BYTES -> SEND RESEARCH 002 -> EXIT 74\n                                            |\n                         RESTART -> FINALIZED LOOKUP\n                                            |\n                    SAME SIGNATURE -> TASK 003 -> DONE')+'<p>The second payment was dispatched before the deliberate exit. Its receipt was not yet persisted. Restart reconciled that exact signature and verified finalized bytes, fee and USDC balance deltas. A repeated complete run left the transaction outbox unchanged: zero new signatures or transfers.</p><p>Signed bytes persist before broadcast. A transport error keeps the transaction held. Reads back off on public-RPC rate limits; an expired uncertain outcome stops for inspection instead of signing a replacement.</p>')+
 sec('guards','05 / CHECK THE BOUNDARY','<p>On actual mainnet accounts, preflight rejected one microUSDC over the remaining cap and a different delegate. Owner revocation finalized; a subsequent worker preflight also rejected. These three negative checks are signed simulations, not broadcast failed transactions. No failed-test fees were spent.</p><p>The downloaded mainnet executable separately passes 15 local LiteSVM checks using fixture balances. The program is upgradeable; this is not an independent BATTERY audit.</p>'+actions(('/evidence/mainnet-canary.json','ACTUAL NEGATIVE CHECKS'),('/evidence/reserve-svm.json','15 LOCAL PROGRAM TESTS')))+
 sec('network','06 / READ MAINNET NOW','<div class="section-top"><p id="live-status" role="status">[ CONNECTING ]</p><button id="refresh-network" class="text-button">[ REFRESH MAINNET ]</button></div><pre id="live-readout" class="code">[ WAITING FOR RPC ]</pre><p id="sample-age" class="fine">[ NO SAMPLE YET ]</p><p class="fine">Fixed read-only endpoint, 30s cache. Network transaction rate is not BATTERY usage. Receipt evidence above is a dated experiment, not a live customer balance.</p>')+
 sec('research','07 / THE OWNED RESEARCHER',code('[ PASS ] MAINNET READS -> QWEN -> EXIT 73 -> LLAMA\n[ PASS ] 3 TASKS / 3 CALLS / 0 DUPLICATES')+f'<p>Actual local model generation, before the settlement test. Restart through completion: {mainExp["restartThroughCompletionSeconds"]}s. Local provider charge was zero; hardware cost is unmeasured.</p>'+actions(('/evidence/mainnet-agent.json','MODEL OUTPUTS + EVENTS')))+mainTasks,'<script type="module" src="/mainnet.mjs"></script>')
 shell('live','Live devnet',head('LIVE / FIXED READ-ONLY INTEGRATION','READ THE SIGNAL.<br>SOLANA DEVNET.','Public Solana devnet, observed by the server.<br>A test network; refresh on demand.')+sec('network','01 / NETWORK PROBE','''<div class="section-top"><p id="live-status" role="status">[ CONNECTING ]</p><button id="refresh-network" class="text-button">[ REFRESH DEVNET ]</button></div><pre id="live-readout" class="code">[ WAITING FOR RPC ]</pre><p id="sample-age" class="fine">[ NO SAMPLE YET ]</p><p class="fine">Live read-only integration. Cache up to 30s. A sample older than 90s is marked stale. Recent transaction rate includes all transactions in that devnet sample; it is not mainnet volume, user demand or BATTERY activity.</p>'''+link('/api/network','RAW API RESPONSE'))+sec('next','02 / CONNECT THE WORK','<p>The owned agent reads this cluster, writes a structured brief, saves its receipt and survives a deliberate process exit. This public console reads data; it does not remotely run the local model.</p>'+actions(('/evidence','ACTUAL MODEL RUN'),('/docs#quickstart','RUN YOUR OWN AGENT'),('/openapi.json','API CONTRACT'))),'<script type="module" src="/live.mjs"></script>')
 from datetime import datetime,timezone
 timeline='\n'.join(datetime.fromtimestamp(e['at'],timezone.utc).strftime('%H:%M:%S')+'  '+e['kind'].upper()+' / '+e.get('job',e.get('model','')) for e in report['events'])
 tasks=''
 for i,r in enumerate(report['checkpoint']['body']['results'],1):
  out=r['output'];inp=out['input']
  tasks+=sec('task-'+str(i),f"TASK {i:02d} / {out['model'].upper()}",'<p>'+esc(out['interpretation']['summary'])+'</p><p class="fine">Actual model output, unedited; interpretation may be wrong. Input finalized slot: '+str(inp['observation']['slot'])+'. Prior completed IDs: '+esc(', '.join(inp['previousCompletedIds']) or 'none')+'.</p>')
 stats=f'''<dl class="proof-stats"><div><dt>COMPLETED TASKS</dt><dd>3 / 3</dd></div><div><dt>DUPLICATE CALLS</dt><dd>0</dd></div><div><dt>RESTART + FINISH</dt><dd>{exp['restartThroughCompletionSeconds']}s</dd></div></dl>'''
 proof=stats+code('QWEN 2.5 7B -> RECEIPT COMMITTED -> EXIT 73\n                                  |\n                           LLAMA 3.2 3B\n                                  |\n                      RECONCILE -> TASK 03 DONE')+'<p>Crash was deliberately triggered after task 2\'s receipt became durable, before ledger settlement. The fallback recovered that receipt without another inference call, then completed task 3 with both prior results in its input.</p><p class="fine">One bounded run on an owned machine, not an uptime SLA. USD ledger is paper. Provider charge: $0 for local inference; hardware/electricity unmeasured. No paid API or arbitrary third-party migration.</p>'+actions(('/evidence/live-agent.json','ALL OUTPUTS + EVENTS / JSON'),(SOURCE,'SOURCE'),(SOURCE+'/actions' if SOURCE else None,'CI'))
 integrity='''<p>Compute SHA256 of the published result body in this browser and compare with the checkpoint. Integrity does not authenticate the model or make its statements true.</p><button id="verify-checkpoint" class="text-button">[ VERIFY HASH LOCALLY ]</button><pre id="integrity-result" class="code" role="status">[ READY TO VERIFY ]</pre>'''
 financial_verify='<button id="verify-financial-proof" class="text-button">[ VERIFY MAINNET ARTIFACT ]</button><pre id="financial-integrity" class="code" role="status">[ READY TO VERIFY MAINNET ARTIFACT ]</pre>'
 financial_lead=financial_summary+'<p>The 5,000 lamports shown on each receipt are the network fee. Each research payment also transferred 0.01 USDC via the existing fixed-delegation program. Its Memo binds a result hash; the Memo itself is not the money transfer.</p>'+actions(('https://explorer.solana.com/tx/'+fb['receipts']['research-001']['signature'],'INSPECT 0.01 USDC TRANSFER'),('/mainnet#receipts','ALL 8 FINALIZED RECEIPTS'))+financial_verify
 devnet_history=code('[ HISTORICAL DEVNET CHECK / NOT SENT ]\nTEST WALLET FUNDED   NO\nRPC FEE QUOTE        5,000 TEST LAMPORTS\nSIGNED BROADCAST     NONE\nFINALIZED SIGNATURE  NONE')+'<p>The devnet faucet returned an error and rate limit. Its test wallet received no test SOL. The RPC accepted an unsigned message for a fee estimate; there is no confirmed devnet Memo. An RPC endpoint is a network service, not the wallet to fund. This earlier failed devnet attempt is separate from the eight finalized mainnet receipts above.</p>'+actions(('/evidence/devnet-fee-quote.json','UNSIGNED DEVNET QUOTE'),('/evidence/devnet-anchor-status.json','FAILED FAUCET / STATUS'),('/docs#devnet','OPTIONAL DEVNET TOOL'))
 economics=code('[ SELF-HOSTED SDK / MIT ] $0\n[ MANAGED OPERATIONS / PROPOSED ] $9 / AGENT / MONTH\nCOMPUTE + GAS        SEPARATE OPERATOR COSTS\nRESERVE PRINCIPAL    OPERATOR CAPITAL\nPAID SUBSCRIPTIONS  NOT AVAILABLE\nMEASURED REVENUE     NONE DEMONSTRATED')+'<p>Proposed revenue: a fixed fee for managed budget checks, durable execution receipts, recovery reconciliation and alerts. The $9 is a reference price to validate with operators; willingness to pay and margin are unverified. Local inference charge $0 describes the historical experiment, not a service tariff.</p>'+actions(('/pricing','PLAN + OPERATING CALCULATOR'),('/developer/pricing.md','ECONOMIC CONTRACT / MD'))
 integrated_proof=json.loads((root/'evidence/integrated-financial.json').read_text()); ib=integrated_proof['body']
 integrated_receipts=actions(*[('https://explorer.solana.com/tx/'+ib['receipts']['research-00'+str(i)]['signature'],'TASK '+str(i)+' / FINALIZED USDC') for i in range(1,4)])
 integrated=code('[ PASS ] LIVE INTERLEAVED MAINNET EXECUTION\nRESERVE CHECK -> MODEL -> DURABLE RESULT\n              -> FINALIZED USDC -> NEXT TASK\n3 UNIQUE MODEL CALLS / 3 x 0.01 USDC\nEXIT 74 -> SAME SIGNATURE -> TASK 03\nREPLAY: 0 NEW CALLS / 0 NEW TRANSFERS\nDELEGATION REVOKED / 5 USDC RETURNED')+'<p>October 5, 2026. New, separately funded run: the controller checked actual allowance, expiry, reserve and gas before each task. Qwen produced the first two results. After a real process exit following the second signed send, Llama reused the saved result, reconciled the same payment signature and completed the third task after finality. The independent verifier checked finalized signed bytes, each result Memo and exact token deltas. A second concurrent CLI runner was refused before inference or signing.</p><p class="fine">Eight finalized transactions in this run, including excess refund, setup, three settlements, revoke and two returns. Total BATTERY network fees: 0.00004 SOL. Test payments went to the owned worker; they are not provider invoices or project revenue. Local inference, prefunded SOL and one trusted operator; hosted paid service and automatic gas refill remain absent.</p>'+integrated_receipts+actions(('/evidence/integrated-runtime/integrated.json','MODEL + AUTHORIZATION + FINALITY EVENTS'),('/evidence/integrated-financial.json','SIGNED FINANCIAL PROOF'),('/developer/integrated-runtime.md','REPRODUCE + VERIFY'))+'<button id="verify-integrated-artifact" class="text-button">[ VERIFY INTEGRATED ARTIFACT HASH ]</button><pre id="integrated-integrity" class="code" role="status">[ READY TO VERIFY INTEGRATED ARTIFACT ]</pre>'
 shell('pricing','Pricing and operating economics',head('PRICING / PROPOSED MANAGED PLAN','PAY FOR CONTINUITY.<br>KEEP YOUR RESERVE.','Free SDK today.<br>Proposed managed fee: $9 / active agent / month.')+sec('plan','01 / THE PROPOSED PLAN',economics+'<p>One registered agent: managed spending checks, retained receipts, reconciliation and operational alerts. Model compute, agent hosting, gas refill and a custody guarantee are outside this proposed fee. No paid entitlement, SLA or checkout is active.</p>')+sec('calculator','02 / TEST THE ECONOMICS','<p>Enter your estimated monthly operating costs for hosting, RPC, storage, support and recovery. The fee is a hypothesis. The calculation is a scenario; it does not report measured BATTERY margin. Provider bills and operator gas are separate from project revenue. Include tax, acquisition and overhead in your cost input if you want them reflected.</p><form id="economics-form"><label for="economics-agents">ACTIVE AGENTS / SCENARIO</label><input id="economics-agents" class="text-input" name="agents" type="number" min="1" max="10000" step="1" value="1" required><label for="economics-cost">TOTAL MONTHLY OPERATING COST / USD</label><input id="economics-cost" class="text-input" name="cost" type="number" min="0" max="10000000" step="0.01" placeholder="Enter your estimate" required><pre id="economics-result" class="code" role="status">[ ENTER AGENTS + MONTHLY OPERATING COST ]</pre></form>')+sec('availability','03 / AVAILABLE NOW','<p>The self-hosted SDK is free. Hosted subscriptions and paid-provider billing are not available. The historical canary returned all USDC principal and generated no service revenue. An external paying operator and measured operating costs remain launch gates.</p>'+actions((SOURCE,'GET THE SDK'),('/docs#integrated','RUNBOOK'),('/evidence','INSPECT THE EVIDENCE'))),'<script type="module" src="/pricing.mjs"></script>')
 shell('evidence','Evidence and its limits',head('PROOF / 05 OCT 2026 / INTERLEAVED MAINNET RUN','THE LOOP SURVIVED.<br>THE RESTART.','Live budget checks. Real model tasks. Finalized USDC.<br>Inspect the ordering and every signature.')+sec('interleaved','01 / GENERATE. SETTLE. CONTINUE.',integrated)+sec('mainnet-proof','02 / EARLIER MAINNET CANARY / SEPARATE RUN',financial_lead)+sec('business','03 / COST IS NOT REVENUE',economics)+sec('proof','04 / LOCAL INFERENCE / PAPER USD LEDGER',proof)+sec('integrity','05 / LOCAL CHECKPOINT INTEGRITY',integrity)+sec('timeline','06 / LOCAL MODEL EVENTS / UTC',code(timeline))+tasks+sec('paid-provider','PAID API / EXECUTION PASS / CONTENT REJECTED','<p>One actual OpenAI generation. Exit75 after receipt commit; two recoveries made no new generation; authenticated GET matched response/usage/output.</p>'+code('INPUT TOKENS     336\nOUTPUT TOKENS    234\nTOTAL TOKENS     570\nCOST ESTIMATE    $0.000509 / NOT AN INVOICE\nACTUAL CHARGE    UNVERIFIED\nCONTENT REVIEW  REJECTED')+'<p>The model misread exit code74 as 74 crashes, and total fees across eight transactions as per-call fees. The raw output is quarantined as a rejected deliverable. No second generation was submitted to repair it; no USDC payment bought this inference.</p>'+actions(('/developer/paid-provider.md','RUNBOOK + LIMITS'),('/evidence/paid-provider.json','API RECORD / REJECTED OUTPUT')))+sec('devnet-history','07 / EARLIER DEVNET ATTEMPT / NOT CONFIRMED',devnet_history),'<script type="module" src="/evidence.mjs"></script><script type="module" src="/integrated-integrity.mjs"></script>')
 quick='unzip battery-pilot-kit.zip -d battery-kit\ncd battery-kit\npython3 -m unittest -v test_battery.py test_live_agent.py test_integrated_runtime.py test_paid_provider.py\npython3 verify_evidence.py\nnode --test devnet/anchor.test.mjs\ncd site\nnode --test test-network.mjs'
 live='ollama pull qwen2.5:7b\nollama pull llama3.2:3b\n# From repo root; start Ollama first.\npython3 run_recovery.py --state-dir live-state/my-first-proof\npython3 verify_evidence.py live-state/my-first-proof/live-agent.json'
 content=sec('quickstart','01 / VERIFY FIRST','<p>Python 3.10+, Node 22+. No package dependencies, accounts or payments for offline checks. Download and extract the source kit. Run commands in a terminal.</p>'+actions((SOURCE,'GITHUB SOURCE'),('/battery-pilot-kit.zip','SOURCE ZIP'))+code(quick)+'<p>45 Python tests check policy, failure, receipt recovery and unknown outcomes. Ten Node tests check memo/API boundaries; eleven price/chain/outbox/financial-proof checks require the optional chain dependencies. Evidence verification checks saved hash/event relationships, not model attestation.</p>')
 content+=sec('runtime','02 / RUN REAL INFERENCE','<p>Install/start <a href="https://docs.ollama.com/quickstart">Ollama</a>. Both approved models need sufficient memory and several GB of disk. They run locally without a paid provider key.</p>'+code(live)+'<p>The controller runs three devnet briefs, forces exit 73 after the second durable receipt, starts Llama, verifies inherited state and writes live-agent.json. Use a fresh state directory; it refuses to overwrite a ledger.</p><p>If dispatch reached the model without a durable receipt, recovery stops with an unknown outcome. Do not delete state and silently repeat that task. The demonstrated boundary is after receipt commit.</p>'+link('/evidence','ACTUAL OUTPUTS'))
 content+=sec('mainnet','MAINNET / BOUNDED USDC CANARY','<p>Our owned researcher now also reads mainnet and survives a real local process exit. Eight mainnet transactions are finalized: 3 test settlements, real financial crash/recovery, no replay payment, owner revoke and all 5 USDC returned. Generation preceded settlement and used local models, not paid-provider billing. The executable separately passes 15 local LiteSVM fixture checks.</p>'+actions(('/mainnet','MAINNET CONSOLE + EVIDENCE'),('/developer/mainnet.md','RUNBOOK + FUNDING BOUNDS')))
 content+=sec('integrated','INTEGRATED / LOCAL AGENT + MAINNET SETTLEMENT',integrated)
 content+=sec('paid','PAID PROVIDER / ONE REQUEST / BILLING UNVERIFIED','<p>One actual OpenAI request survived exit75 after durable receipt storage. Two recoveries made no new generation; authenticated GET matched identity, usage and output. 570 tokens; calculated estimate $0.000509. Authoritative charge remains unverified.</p><p>API execution passed; the generated report failed content review. It misread exit code74 as 74 crashes and total network fees as per-call fees. The output remains rejected. Sixteen offline checks cover the adapter, content gate and proof integrity. Usage multiplied by prices is an estimate, never an invoice, credit or Solana payment.</p>'+actions(('/developer/paid-provider.md','CONTRACT + OPERATOR RUNBOOK'),('/evidence/paid-provider.json','RAW API RECORD / REJECTED OUTPUT'),(SOURCE+'/blob/main/paid_provider.py','INSPECT ADAPTER')))
 content+=sec('pricing','COSTS / COMMERCIAL MODEL / NOT A LIVE OFFER',economics)
 content+=sec('integration','03 / ADAPTER CONTRACT','<ol class="workflow"><li>Configure floor, daily cap and per-job ceiling in integer microUSD.</li><li>Reserve a worst-case quote against both reserve and trusted provider headroom. Approve each route before dispatch.</li><li>Mark dispatch before the external effect. Persist actual receipt and result durably.</li><li>Reconcile incurred cost, including charged failures. Overcharges are booked and halt new work.</li><li>Take over the same ledger with a new epoch. Reconcile saved receipts; hold unknown outcomes. Export confirmed results.</li></ol><p>core.py: configure, credit_paper, takeover, reserve, dispatch, settle, checkpoint. live_agent.py is the working Ollama example. Keep credentials outside task/checkpoint JSON.</p>'+actions(('/developer/adapters.md','SDK EXAMPLE'),('/developer/architecture.md','ARCHITECTURE')))
 content+=sec('api','04 / LIVE PUBLIC API',code('GET https://usebattery.xyz/api/network   # devnet\nGET https://usebattery.xyz/api/mainnet   # mainnet')+'<p>No key, body or query parameters. Returns genesis, finalized slot/epoch/block height and recent performance sample with UNIX observedAt. Sample slot may precede the observation. Cache up to 30s; public RPC may fail.</p><p>405 for writes, 400 for parameters, 502 for invalid/unavailable upstream. Errors contain no synthetic numbers. This API cannot sign, spend or trigger model inference.</p>'+actions(('/live','LIVE CONSOLE'),('/openapi.json','OPENAPI')))
 content+=sec('devnet','05 / OPTIONAL SIGNED CHECKPOINT',code('node devnet/anchor.mjs anchor live-state/my-first-proof/live-agent.json devnet-state/my-first-proof --airdrop\nnode devnet/anchor.mjs verify devnet-state/my-first-proof/anchor.json')+'<p>Test network only, fresh local test key, exact devnet genesis. Protects 0.5 test SOL, max fee 10,000 lamports, daily fees 30,000. Quote before signing; persist bytes before sending; retry the same signature only. Expiry requires inspection, not automatic re-signing.</p><p>Faucet refused this run, so no signature is claimed. A Memo would bind a hash to a devnet slot, not prove model truth, deploy custody or fund paid inference. Private keys never enter the public kit or Vercel.</p>')
 content+=sec('limits','06 / GUARANTEE BOUNDARY','<p>Trusted local operator, one SQLite ledger. Quote/time/provider headroom are trusted inputs. No authenticated paid billing, distributed lease, arbitrary framework/browser migration, hosted customer agent or USDC custody.</p><p>Copying a checkpoint does not transfer authority. Unknown effects stay held; stronger guarantees need provider idempotency/authenticated receipts. No BATTERY token or custody program is deployed. The completed USDC canary used the existing Solana Subscriptions program.</p><p>Browser lab: one illustrative task/hour, $30 daily cap, $500 alternate allowance, cheaper route at 40% cost, assumed fees $2/hour. Not a prediction. The 72 logical-hour replay is simulated; the hourly observer had gaps.</p>'+link('/developer/security.md','SECURITY MODEL'))
 content+=sec('privacy','07 / YOUR DATA','<p>Policies/test history use browser local storage, separate per domain. No account/cloud sync. Export before clearing data/moving devices. Imports validate and merge IDs, retain existing records: max 100 policies, 200 tests, 250 KB.</p><p>Scenario links expose parameters in the fragment, not names/history. Keep secrets out. AI ledgers stay local; published proof contains selected observations, outputs and events. The fixed public endpoints read devnet/mainnet on the server; hosting may process ordinary request metadata.</p>'+link('/assets/brand/battery-brand-kit.zip','ASCII BRAND KIT'))
 content+=sec('research','08 / RESEARCH ENTRY POINTS','<p>The agent brief explains the hypothesis, evidence and open questions. It supports independent assessment.</p>'+actions(('/agents.md','AGENTS.MD'),('/llms.txt','LLMS.TXT'),('/llms-full.txt','COMPLETE TEXT DOCS')))
 nav='<nav class="docs-nav" aria-label="Documentation">'+''.join(link('#'+id,name) for id,name in [('quickstart','START'),('runtime','REAL AGENT'),('mainnet','MAINNET'),('integrated','INTERLEAVED'),('paid','PAID PROVIDER'),('pricing','COSTS'),('integration','SDK'),('api','LIVE API'),('devnet','DEVNET'),('limits','LIMITS'),('privacy','DATA'),('research','RESEARCH')])+'</nav>'
 shell('docs','Developer docs',head('DOCS / v0.3 / SOURCE + REPRODUCTION','READ THE CONTRACT.<br>RUN THE PROOF.','One owned-agent integration.<br>Build on what is demonstrated.')+'<div class="docs-layout">'+nav+'<div>'+content+'</div></div>','<script type="module" src="/integrated-integrity.mjs"></script>')
 shell('agents','For research agents',head('RESEARCH / MACHINE-READABLE ENTRY POINT','FOLLOW THE EVIDENCE.','Source, boundaries and reproducible results.')+sec('brief','01 / START HERE','<p>BATTERY connects allocated operator budget, provider authorization and recoverable work. That seam is the hypothesis; demand remains unverified. Real local inference and live devnet now give researchers something concrete to inspect.</p>'+actions(('/agents.md','READ AGENTS.MD'),('/llms-full.txt','COMPLETE DOCS'),('/openapi.json','API SCHEMA')))+sec('sources','02 / TEST THE CLAIMS','<p>Inspect actual outputs and events. Verify the hash. Run tests and reproduce recovery with your own models. Internal integrity does not make a generated interpretation true.</p>'+actions(('/evidence','HUMAN PROOF'),(SOURCE,'SOURCE'),(SOURCE+'/actions' if SOURCE else None,'CI'),('/docs#quickstart','REPRODUCE'))))
 (D/'evidence').mkdir(exist_ok=True)
 for name in ['live-agent.json','devnet-anchor-status.json','devnet-fee-quote.json','mainnet-agent.json','reserve-svm.json','mainnet-status.json','mainnet-canary.json','integrated-financial.json','paid-provider.json']:shutil.copyfile(root/'evidence'/name,D/'evidence'/name)
 shutil.copytree(root/'evidence/integrated-runtime',D/'evidence/integrated-runtime',dirs_exist_ok=True)
 shutil.copyfile(root/'docs/agents.md',D/'agents.md')
 (D/'developer').mkdir(exist_ok=True)
 for name in ['adapters.md','architecture.md','security.md','mainnet.md','pricing.md','integrated-runtime.md','paid-provider.md','product-contract.md']:shutil.copyfile(root/'docs'/name,D/'developer'/name)
 (D/'llms.txt').write_text(f'# BATTERY\n> Reserve policy and controlled recovery for owned agents. Developer SDK v0.3; completed bounded mainnet canary.\n\n## Documentation\n- [Research brief]({BASE}/agents.md): hypothesis, evidence and limits.\n- [Full text]({BASE}/llms-full.txt): README, architecture, adapters and security.\n- [Developer docs]({BASE}/docs): reproduce actual inference and recovery.\n- [Integrated execution]({BASE}/developer/integrated-runtime.md): completed interleaved local/mainnet run;3 actual calls/3 finalized settlements, same-signature recovery and all principal returned.\n- [Paid-provider adapter]({BASE}/developer/paid-provider.md): one actual request/recovery/readback; report rejected, authoritative billing unverified.\n- [Pricing]({BASE}/pricing): proposed $9/active-agent/month; unavailable for purchase.\n- [Costs and commercial hypothesis]({BASE}/developer/pricing.md): free SDK; hosted pricing, paid costs and revenue unvalidated.\n- [OpenAPI]({BASE}/openapi.json): fixed read-only devnet API.\n\n## Evidence\n- [Actual local AI run]({BASE}/evidence/live-agent.json): dated inference, crash and recovery.\n- [Mainnet financial proof]({BASE}/mainnet):8 finalized transactions,3 test settlements,crash/recovery,revoke and5USDC return.\n- [Financial artifact]({BASE}/evidence/mainnet-canary.json): signatures,wire hashes,exact USDC deltas,negative simulations and verifier.\n- [Canary runbook]({BASE}/developer/mainnet.md): bounded USDC delegation, safety and return path.\n- [Human proof]({BASE}/evidence): event trail and browser hash check.\n- [Anchor status]({BASE}/evidence/devnet-anchor-status.json): unconfirmed; faucet refused test SOL.\n- [GitHub source]({SOURCE}): public SDK repository.\n- [Source kit]({BASE}/battery-pilot-kit.zip): SDK, tests and website source.\n\n## Boundary\nActual local inference/devnet reads; paper USD/browser simulations. Eight mainnet canary transactions are finalized; test transfers bind saved results, not paid-model billing. Three negative mainnet checks in each run were preflight simulations. New integrated proof: {BASE}/evidence/integrated-financial.json; model/event trail: {BASE}/evidence/integrated-runtime/integrated.json. No hosted paid agent,vault,token or independent BATTERY audit.\n')
 (D/'llms-full.txt').write_text('\n\n---\n\n'.join((root/n).read_text() for n in ['docs/agents.md','README.md','docs/architecture.md','docs/adapters.md','docs/security.md','docs/pricing.md','docs/integrated-runtime.md','docs/paid-provider.md','docs/product-contract.md']))
 props={'schema':{'const':'battery.network/1'},'cluster':{'const':'devnet'},'rpc':{'const':'https://api.devnet.solana.com'},'genesisHash':{'const':'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG'},**{k:{'type':'integer','minimum':0} for k in ['observedAt','slot','epoch','blockHeight','latencyMs']},'performance':{'type':'object','required':['slot','numTransactions','samplePeriodSecs','transactionsPerSecond'],'properties':{'slot':{'type':'integer'},'numTransactions':{'type':'integer'},'samplePeriodSecs':{'type':'integer','minimum':1},'transactionsPerSecond':{'type':'number','minimum':0}}}}
 schema={'type':'object','required':list(props),'properties':props}
 error={'description':'Structured error; no synthetic observation','content':{'application/json':{'schema':{'type':'object','required':['error','message'],'properties':{'error':{'type':'string'},'message':{'type':'string'}}}}}}
 api={'openapi':'3.1.0','info':{'title':'BATTERY live devnet API','version':'0.2.0','description':'Fixed read-only devnet, 30s cache. No auth, parameters, signing, spending or model calls.'},'servers':[{'url':BASE}],'paths':{'/api/network':{'get':{'operationId':'getDevnetObservation','summary':'Read validated public devnet observation','responses':{'200':{'description':'Actual observation, observedAt UNIX UTC. Sample slot may differ from finalized slot.','content':{'application/json':{'schema':schema}}},'400':error,'405':error,'502':error}}}}}
 import copy
 mainnet_api=copy.deepcopy(api['paths']['/api/network'])
 mainnet_api['get']['operationId']='getMainnetObservation'
 mainnet_api['get']['summary']='Read validated public mainnet observation'
 main_props=mainnet_api['get']['responses']['200']['content']['application/json']['schema']['properties']
 main_props['cluster']={'const':'mainnet'};main_props['rpc']={'const':'https://api.mainnet-beta.solana.com'};main_props['genesisHash']={'const':'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d'}
 api['paths']['/api/mainnet']=mainnet_api
 api['info'].update(title='BATTERY read-only Solana API',version='0.3.0',description='Fixed devnet/mainnet endpoints, independent 30s caches. No auth, parameters, signing, spending or model calls.')
 (D/'openapi.json').write_text(json.dumps(api,indent=2)+'\n')
