from pathlib import Path
import html,json,shutil
# Optional repository URL. Leave unset until the new owner is confirmed.
SOURCE='https://github.com/sproutagentai/battery-agent-reserve'
def build(shell,head,panel,D,BASE):
 root=Path(__file__).resolve().parent.parent
 report=json.loads((root/'evidence/live-agent.json').read_text()); exp=report['experiment']
 esc=html.escape
 def code(t):return '<pre class="code">'+esc(t)+'</pre>'
 def sec(id,title,body):return f'<section id="{id}" class="panel"><h2>{title}</h2>{body}</section>'
 def link(url,label):return f'<a class="text-button" href="{url}">[ {label} ]</a>'
 def actions(*links):return '<div class="actions">'+''.join(link(*l) for l in links if l[0])+'</div>'
 shell('live','Live devnet',head('LIVE / FIXED READ-ONLY INTEGRATION','READ THE SIGNAL.<br>SOLANA DEVNET.','Public Solana devnet, observed by the server.<br>A test network; refresh on demand.')+sec('network','01 / NETWORK PROBE','''<div class="section-top"><p id="live-status" role="status">[ CONNECTING ]</p><button id="refresh-network" class="text-button">[ REFRESH DEVNET ]</button></div><pre id="live-readout" class="code">[ WAITING FOR RPC ]</pre><p id="sample-age" class="fine">[ NO SAMPLE YET ]</p><p class="fine">Live read-only integration. Cache up to 30s. A sample older than 90s is marked stale. Recent transaction rate includes all transactions in that devnet sample; it is not mainnet volume, user demand or BATTERY activity.</p>'''+link('/api/network','RAW API RESPONSE'))+sec('next','02 / CONNECT THE WORK','<p>The owned agent reads this cluster, writes a structured brief, saves its receipt and survives a deliberate process exit. This public console reads data; it does not remotely run the local model.</p>'+actions(('/evidence','ACTUAL MODEL RUN'),('/docs#quickstart','RUN YOUR OWN AGENT'),('/openapi.json','API CONTRACT'))),'<script type="module" src="/live.mjs"></script>')
 from datetime import datetime,timezone
 timeline='\n'.join(datetime.fromtimestamp(e['at'],timezone.utc).strftime('%H:%M:%S')+'  '+e['kind'].upper()+' / '+e.get('job',e.get('model','')) for e in report['events'])
 tasks=''
 for i,r in enumerate(report['checkpoint']['body']['results'],1):
  out=r['output'];inp=out['input']
  tasks+=sec('task-'+str(i),f"TASK {i:02d} / {out['model'].upper()}",'<p>'+esc(out['interpretation']['summary'])+'</p><p class="fine">Actual model output, unedited; interpretation may be wrong. Input finalized slot: '+str(inp['observation']['slot'])+'. Prior completed IDs: '+esc(', '.join(inp['previousCompletedIds']) or 'none')+'.</p>')
 stats=f'''<dl class="proof-stats"><div><dt>COMPLETED TASKS</dt><dd>3 / 3</dd></div><div><dt>DUPLICATE CALLS</dt><dd>0</dd></div><div><dt>RESTART + FINISH</dt><dd>{exp['restartThroughCompletionSeconds']}s</dd></div></dl>'''
 proof=stats+code('QWEN 2.5 7B -> RECEIPT COMMITTED -> EXIT 73\n                                  |\n                           LLAMA 3.2 3B\n                                  |\n                      RECONCILE -> TASK 03 DONE')+'<p>Crash was deliberately triggered after task 2\'s receipt became durable, before ledger settlement. The fallback recovered that receipt without another inference call, then completed task 3 with both prior results in its input.</p><p class="fine">One bounded run on an owned machine, not an uptime SLA. USD ledger is paper. Provider charge: $0 for local inference; hardware/electricity unmeasured. No paid API or arbitrary third-party migration.</p>'+actions(('/evidence/live-agent.json','ALL OUTPUTS + EVENTS / JSON'),(SOURCE,'SOURCE'),(SOURCE+'/actions' if SOURCE else None,'CI'))
 integrity='''<p>Compute SHA256 of the published result body in this browser and compare with the checkpoint. Integrity does not authenticate the model or make its statements true.</p><button id="verify-checkpoint" class="text-button">[ VERIFY HASH LOCALLY ]</button><pre id="integrity-result" class="code" role="status">[ READY TO VERIFY ]</pre>'''
 chain='<p>Actual devnet reads are integrated. RPC accepted the bounded Memo message and quoted 5,000 test lamports. The signing tool is implemented and offline tested; faucet refused funding. This experiment has no confirmed onchain signature. No custody vault, real USD reserve or token is deployed.</p>'+actions(('/evidence/devnet-fee-quote.json','ACTUAL FEE QUOTE'),('/evidence/devnet-anchor-status.json','ANCHOR STATUS / JSON'),('/docs#devnet','DEVNET TOOL'),('/docs#quickstart','REPRODUCE'))
 shell('evidence','Actual recovery proof',head('PROOF / 05 OCT 2026 / DATED LOCAL EXPERIMENT','PULL THE PROCESS.<br>KEEP THE WORK.','Actual local inference. Actual devnet reads.<br>Receipt survived. Next task continued.')+sec('proof','01 / OBSERVED RESULT',proof)+sec('integrity','02 / VERIFY THE CHECKPOINT',integrity)+sec('timeline','03 / EVENT TRAIL / UTC',code(timeline))+tasks+sec('chain','04 / CHAIN BOUNDARY',chain),'<script type="module" src="/evidence.mjs"></script>')
 quick='unzip battery-pilot-kit.zip -d battery-kit\ncd battery-kit\npython3 -m unittest -v test_battery.py test_live_agent.py\npython3 verify_evidence.py\nnode --test devnet/anchor.test.mjs\ncd site\nnode --test test-network.mjs'
 live='ollama pull qwen2.5:7b\nollama pull llama3.2:3b\n# From repo root; start Ollama first.\npython3 run_recovery.py --state-dir live-state/my-first-proof\npython3 verify_evidence.py live-state/my-first-proof/live-agent.json'
 content=sec('quickstart','01 / VERIFY FIRST','<p>Python 3.10+, Node 22+. No package dependencies, accounts or payments for offline checks. Download and extract the source kit. Run commands in a terminal.</p>'+actions((SOURCE,'GITHUB SOURCE'),('/battery-pilot-kit.zip','SOURCE ZIP'))+code(quick)+'<p>18 Python tests check policy, failure, receipt recovery and unknown outcomes. Eight Node tests check memo/API boundaries. Evidence verification checks saved hash/event relationships, not model attestation.</p>')
 content+=sec('runtime','02 / RUN REAL INFERENCE','<p>Install/start <a href="https://docs.ollama.com/quickstart">Ollama</a>. Both approved models need sufficient memory and several GB of disk. They run locally without a paid provider key.</p>'+code(live)+'<p>The controller runs three devnet briefs, forces exit 73 after the second durable receipt, starts Llama, verifies inherited state and writes live-agent.json. Use a fresh state directory; it refuses to overwrite a ledger.</p><p>If dispatch reached the model without a durable receipt, recovery stops with an unknown outcome. Do not delete state and silently repeat that task. The demonstrated boundary is after receipt commit.</p>'+link('/evidence','ACTUAL OUTPUTS'))
 content+=sec('integration','03 / ADAPTER CONTRACT','<ol class="workflow"><li>Configure floor, daily cap and per-job ceiling in integer microUSD.</li><li>Reserve a worst-case quote against both reserve and trusted provider headroom. Approve each route before dispatch.</li><li>Mark dispatch before the external effect. Persist actual receipt and result durably.</li><li>Reconcile incurred cost, including charged failures. Overcharges are booked and halt new work.</li><li>Take over the same ledger with a new epoch. Reconcile saved receipts; hold unknown outcomes. Export confirmed results.</li></ol><p>core.py: configure, credit_paper, takeover, reserve, dispatch, settle, checkpoint. live_agent.py is the working Ollama example. Keep credentials outside task/checkpoint JSON.</p>'+actions(('/developer/adapters.md','SDK EXAMPLE'),('/developer/architecture.md','ARCHITECTURE')))
 content+=sec('api','04 / LIVE PUBLIC API',code('GET https://usebattery.xyz/api/network')+'<p>No key, body or query parameters. Returns genesis, finalized slot/epoch/block height and recent performance sample with UNIX observedAt. Sample slot may precede the observation. Cache up to 30s; public RPC may fail.</p><p>405 for writes, 400 for parameters, 502 for invalid/unavailable upstream. Errors contain no synthetic numbers. This API cannot sign, spend or trigger model inference.</p>'+actions(('/live','LIVE CONSOLE'),('/openapi.json','OPENAPI')))
 content+=sec('devnet','05 / OPTIONAL SIGNED CHECKPOINT',code('node devnet/anchor.mjs anchor live-state/my-first-proof/live-agent.json devnet-state/my-first-proof --airdrop\nnode devnet/anchor.mjs verify devnet-state/my-first-proof/anchor.json')+'<p>Test network only, fresh local test key, exact devnet genesis. Protects 0.5 test SOL, max fee 10,000 lamports, daily fees 30,000. Quote before signing; persist bytes before sending; retry the same signature only. Expiry requires inspection, not automatic re-signing.</p><p>Faucet refused this run, so no signature is claimed. A Memo would bind a hash to a devnet slot, not prove model truth, deploy custody or fund paid inference. Private keys never enter the public kit or Vercel.</p>')
 content+=sec('limits','06 / GUARANTEE BOUNDARY','<p>Trusted local operator, one SQLite ledger. Quote/time/provider headroom are trusted inputs. No authenticated paid billing, distributed lease, arbitrary framework/browser migration, hosted customer agent or USDC custody.</p><p>Copying a checkpoint does not transfer authority. Unknown effects stay held; stronger guarantees need provider idempotency/authenticated receipts. No token or contract address exists.</p><p>Browser lab: one illustrative task/hour, $30 daily cap, $500 alternate allowance, cheaper route at 40% cost, assumed fees $2/hour. Not a prediction. The 72 logical-hour replay is simulated; the hourly observer had gaps.</p>'+link('/developer/security.md','SECURITY MODEL'))
 content+=sec('privacy','07 / YOUR DATA','<p>Policies/test history use browser local storage, separate per domain. No account/cloud sync. Export before clearing data/moving devices. Imports validate and merge IDs, retain existing records: max 100 policies, 200 tests, 250 KB.</p><p>Scenario links expose parameters in the fragment, not names/history. Keep secrets out. AI ledgers stay local; published proof contains selected observations, outputs and events. The public API reads devnet on the server; hosting may process ordinary request metadata.</p>'+link('/assets/brand/battery-brand-kit.zip','ASCII BRAND KIT'))
 content+=sec('research','08 / RESEARCH ENTRY POINTS','<p>The agent brief explains the hypothesis, evidence and open questions. It supports independent assessment.</p>'+actions(('/agents.md','AGENTS.MD'),('/llms.txt','LLMS.TXT'),('/llms-full.txt','COMPLETE TEXT DOCS')))
 nav='<nav class="docs-nav" aria-label="Documentation">'+''.join(link('#'+id,name) for id,name in [('quickstart','START'),('runtime','REAL AGENT'),('integration','SDK'),('api','LIVE API'),('devnet','DEVNET'),('limits','LIMITS'),('privacy','DATA'),('research','RESEARCH')])+'</nav>'
 shell('docs','Developer docs',head('DOCS / v0.2 / SOURCE + REPRODUCTION','READ THE CONTRACT.<br>RUN THE PROOF.','One owned-agent integration.<br>Build on what is demonstrated.')+'<div class="docs-layout">'+nav+'<div>'+content+'</div></div>')
 shell('agents','For research agents',head('RESEARCH / MACHINE-READABLE ENTRY POINT','FOLLOW THE EVIDENCE.','Source, boundaries and reproducible results.')+sec('brief','01 / START HERE','<p>BATTERY connects allocated operator budget, provider authorization and recoverable work. That seam is the hypothesis; demand remains unverified. Real local inference and live devnet now give researchers something concrete to inspect.</p>'+actions(('/agents.md','READ AGENTS.MD'),('/llms-full.txt','COMPLETE DOCS'),('/openapi.json','API SCHEMA')))+sec('sources','02 / TEST THE CLAIMS','<p>Inspect actual outputs and events. Verify the hash. Run tests and reproduce recovery with your own models. Internal integrity does not make a generated interpretation true.</p>'+actions(('/evidence','HUMAN PROOF'),(SOURCE,'SOURCE'),(SOURCE+'/actions' if SOURCE else None,'CI'),('/docs#quickstart','REPRODUCE'))))
 (D/'evidence').mkdir(exist_ok=True)
 for name in ['live-agent.json','devnet-anchor-status.json','devnet-fee-quote.json']:shutil.copyfile(root/'evidence'/name,D/'evidence'/name)
 shutil.copyfile(root/'docs/agents.md',D/'agents.md')
 (D/'developer').mkdir(exist_ok=True)
 for name in ['adapters.md','architecture.md','security.md']:shutil.copyfile(root/'docs'/name,D/'developer'/name)
 (D/'llms.txt').write_text(f'# BATTERY\n> Reserve policy and controlled recovery for owned agents. Developer SDK v0.2.\n\n## Documentation\n- [Research brief]({BASE}/agents.md): hypothesis, evidence and limits.\n- [Full text]({BASE}/llms-full.txt): README, architecture, adapters and security.\n- [Developer docs]({BASE}/docs): reproduce actual inference and recovery.\n- [OpenAPI]({BASE}/openapi.json): fixed read-only devnet API.\n\n## Evidence\n- [Actual local AI run]({BASE}/evidence/live-agent.json): dated inference, crash and recovery.\n- [Human proof]({BASE}/evidence): event trail and browser hash check.\n- [Anchor status]({BASE}/evidence/devnet-anchor-status.json): unconfirmed; faucet refused test SOL.\n- [GitHub source]({SOURCE}): public SDK repository.\n- [Source kit]({BASE}/battery-pilot-kit.zip): SDK, tests and website source.\n\n## Boundary\nActual local inference/devnet reads; paper USD/browser simulations. No hosted paid agent, vault, token or mainnet payments.\n')
 (D/'llms-full.txt').write_text('\n\n---\n\n'.join((root/n).read_text() for n in ['docs/agents.md','README.md','docs/architecture.md','docs/adapters.md','docs/security.md']))
 props={'schema':{'const':'battery.network/1'},'cluster':{'const':'devnet'},'rpc':{'const':'https://api.devnet.solana.com'},'genesisHash':{'const':'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG'},**{k:{'type':'integer','minimum':0} for k in ['observedAt','slot','epoch','blockHeight','latencyMs']},'performance':{'type':'object','required':['slot','numTransactions','samplePeriodSecs','transactionsPerSecond'],'properties':{'slot':{'type':'integer'},'numTransactions':{'type':'integer'},'samplePeriodSecs':{'type':'integer','minimum':1},'transactionsPerSecond':{'type':'number','minimum':0}}}}
 schema={'type':'object','required':list(props),'properties':props}
 error={'description':'Structured error; no synthetic observation','content':{'application/json':{'schema':{'type':'object','required':['error','message'],'properties':{'error':{'type':'string'},'message':{'type':'string'}}}}}}
 api={'openapi':'3.1.0','info':{'title':'BATTERY live devnet API','version':'0.2.0','description':'Fixed read-only devnet, 30s cache. No auth, parameters, signing, spending or model calls.'},'servers':[{'url':BASE}],'paths':{'/api/network':{'get':{'operationId':'getDevnetObservation','summary':'Read validated public devnet observation','responses':{'200':{'description':'Actual observation, observedAt UNIX UTC. Sample slot may differ from finalized slot.','content':{'application/json':{'schema':schema}}},'400':error,'405':error,'502':error}}}}}
 (D/'openapi.json').write_text(json.dumps(api,indent=2)+'\n')
